/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include <unity/unity.h>
#include <setjmp.h>
#include <stdio.h>
#include "gen/gen_count_string.h"

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_count_string_size_internals(void);
extern void test_count_string_alloc_failure(void);
extern void test_count_string_increment_buffer(void);
extern void test_count_string_set_internals(void);
extern void test_count_string_init(void);


//=======Test Reset Option=====
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  UnityBegin("../test/gen_gen_count_string_test.c");
  RUN_TEST(test_count_string_size_internals, 27);
  RUN_TEST(test_count_string_alloc_failure, 47);
  RUN_TEST(test_count_string_increment_buffer, 72);
  RUN_TEST(test_count_string_set_internals, 87);
  RUN_TEST(test_count_string_init, 119);

  return (UnityEnd());
}
