/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include <setjmp.h>
#include <stdio.h>
#include "unity.h"
#include "memory/memory_put_array.h"

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_assign_memory_put_array(void);
extern void test_assign_memory_put_array_then_put_array(void);
extern void test_memory_put(void);


//=======Test Reset Option=====
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  UnityBegin("../test/memory_memory_put_array_test.c");
  RUN_TEST(test_assign_memory_put_array, 12);
  RUN_TEST(test_assign_memory_put_array_then_put_array, 69);
  RUN_TEST(test_memory_put, 102);

  return (UnityEnd());
}
