/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include <setjmp.h>
#include <stdio.h>
#include "unity.h"
#include "mysql_seed_file.h"

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_file_handle_proccess_success(void);
extern void test_file_handle_proccess_failure(void);
extern void test_unlink_test_file(void);
extern void test_flag_match(void);
extern void test_flag_match_count(void);


//=======Test Reset Option=====
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  UnityBegin("../test/mysql_seed_file_test.c");
  RUN_TEST(test_file_handle_proccess_success, 59);
  RUN_TEST(test_file_handle_proccess_failure, 83);
  RUN_TEST(test_unlink_test_file, 90);
  RUN_TEST(test_flag_match, 96);
  RUN_TEST(test_flag_match_count, 115);

  return (UnityEnd());
}
