/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include <setjmp.h>
#include <stdio.h>
#include "unity.h"
#include "random/random.h"
#include <string.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_random_uint32_from(void);
extern void test_random_int32_from(void);
extern void test_random_uint64_from(void);
extern void test_random_int64_from(void);
extern void test_random_uint32_upto(void);
extern void test_random_int32_upto(void);
extern void test_random_uint64_upto(void);
extern void test_random_int64_upto(void);


//=======Test Reset Option=====
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  UnityBegin("../test/random_random_test.c");
  RUN_TEST(test_random_uint32_from, 15);
  RUN_TEST(test_random_int32_from, 50);
  RUN_TEST(test_random_uint64_from, 85);
  RUN_TEST(test_random_int64_from, 120);
  RUN_TEST(test_random_uint32_upto, 156);
  RUN_TEST(test_random_int32_upto, 191);
  RUN_TEST(test_random_uint64_upto, 226);
  RUN_TEST(test_random_int64_upto, 261);

  return (UnityEnd());
}
