#ifndef MYSQL_SEED_STRING_INT_STRING_ATTRS_H_
#define MYSQL_SEED_STRING_INT_STRING_ATTRS_H_

/* external dependencies
 *─────────────────────────────────────────────────────────────────────────── */
#include <inttypes.h>	/* UINTMAX_MAX, <stdint.h> */

/* constants
 *─────────────────────────────────────────────────────────────────────────── */
/* UINT8_MAX  = 255			(3  digits) */
/* UINT16_MAX = 65535			(5  digits) */
/* UINT32_MAX = 4294967295		(10 digits) */
/* UINT64_MAX = 18446744073709551615	(20 digits) */

#define DIGIT_COUNT_UINT64_MAX	20u
#define DIGIT_COUNT_INT64_MAX	19u
#define DIGIT_COUNT_INT64_MIN	19u
#define DIGIT_STRING_UINT64_MAX	"18446744073709551615"
#define DIGIT_STRING_INT64_MAX	"9223372036854775807"
#define DIGIT_STRING_INT64_MIN	"9223372036854775808"

#define DIGIT_COUNT_UINT32_MAX	10u
#define DIGIT_COUNT_INT32_MAX	10u
#define DIGIT_COUNT_INT32_MIN	10u
#define DIGIT_STRING_UINT32_MAX	"4294967295"
#define DIGIT_STRING_INT32_MAX	"2147483647"
#define DIGIT_STRING_INT32_MIN	"2147483648"

#define DIGIT_COUNT_UINT16_MAX  5u
#define DIGIT_COUNT_INT16_MAX	5u
#define DIGIT_COUNT_INT16_MIN	5u
#define DIGIT_STRING_UINT16_MAX	"65535"
#define DIGIT_STRING_INT16_MAX	"32767"
#define DIGIT_STRING_INT16_MIN	"32768"

#define DIGIT_COUNT_UINT8_MAX   3u
#define DIGIT_COUNT_INT8_MAX	3u
#define DIGIT_COUNT_INT8_MIN	3u
#define DIGIT_STRING_UINT8_MAX	"255"
#define DIGIT_STRING_INT8_MAX	"127"
#define DIGIT_STRING_INT8_MIN	"128"

#if   (UINTMAX_MAX == UINT64_MAX)
#	define HAVE_INT_STRING_ATTRS	1
#	define DIGIT_COUNT_UINTMAX_MAX	DIGIT_COUNT_UINT64_MAX
#	define DIGIT_COUNT_INTMAX_MAX	DIGIT_COUNT_INT64_MAX
#	define DIGIT_COUNT_INTMAX_MIN	DIGIT_COUNT_INT64_MIN
#	define DIGIT_STRING_UINTMAX_MAX	DIGIT_STRING_UINT64_MAX
#	define DIGIT_STRING_INTMAX_MAX	DIGIT_STRING_INT64_MAX
#	define DIGIT_STRING_INTMAX_MIN	DIGIT_STRING_INT64_MIN
#elif (UINTMAX_MAX == UINT32_MAX)
#	define HAVE_INT_STRING_ATTRS	1
#	define DIGIT_COUNT_UINTMAX_MAX	DIGIT_COUNT_UINT32_MAX
#	define DIGIT_COUNT_INTMAX_MAX	DIGIT_COUNT_INT32_MAX
#	define DIGIT_COUNT_INTMAX_MIN	DIGIT_COUNT_INT32_MIN
#	define DIGIT_STRING_UINTMAX_MAX	DIGIT_STRING_UINT32_MAX
#	define DIGIT_STRING_INTMAX_MAX	DIGIT_STRING_INT32_MAX
#	define DIGIT_STRING_INTMAX_MIN	DIGIT_STRING_INT32_MIN
#elif (UINTMAX_MAX == UINT16_MAX)
#	define HAVE_INT_STRING_ATTRS	1
#	define DIGIT_COUNT_UINTMAX_MAX	DIGIT_COUNT_UINT16_MAX
#	define DIGIT_COUNT_INTMAX_MAX	DIGIT_COUNT_INT16_MAX
#	define DIGIT_COUNT_INTMAX_MIN	DIGIT_COUNT_INT16_MIN
#	define DIGIT_STRING_UINTMAX_MAX	DIGIT_STRING_UINT16_MAX
#	define DIGIT_STRING_INTMAX_MAX	DIGIT_STRING_INT16_MAX
#	define DIGIT_STRING_INTMAX_MIN	DIGIT_STRING_INT16_MIN
#elif (UINTMAX_MAX == UINT8_MAX)
#	define HAVE_INT_STRING_ATTRS	1
#	define DIGIT_COUNT_UINTMAX_MAX	DIGIT_COUNT_UINT8_MAX
#	define DIGIT_COUNT_INTMAX_MAX	DIGIT_COUNT_INT8_MAX
#	define DIGIT_COUNT_INTMAX_MIN	DIGIT_COUNT_INT8_MIN
#	define DIGIT_STRING_UINTMAX_MAX	DIGIT_STRING_UINT8_MAX
#	define DIGIT_STRING_INTMAX_MAX	DIGIT_STRING_INT8_MAX
#	define DIGIT_STRING_INTMAX_MIN	DIGIT_STRING_INT8_MIN
#else
#	define HAVE_INT_STRING_ATTRS	0
#	undef  DIGIT_COUNT_UINTMAX_MAX
#	undef  DIGIT_COUNT_INTMAX_MAX
#	undef  DIGIT_COUNT_INTMAX_MIN
#	undef  DIGIT_STRING_UINTMAX_MAX
#	undef  DIGIT_STRING_INTMAX_MAX
#	undef  DIGIT_STRING_INTMAX_MIN
#endif	/* if (UINTMAX_MAX == UINT64_MAX) */

#endif /* ifndef MYSQL_SEED_STRING_INT_STRING_ATTRS_H_ */
